# Part 1: Gaussian Elimination

$$
A = \begin{bmatrix}
2 & -1 & 3 & 7\\
4 & 4 & 0 & 7 \\
2 & 1 & 1 & 3 \\
6 & 5 & 4 & 17
\end{bmatrix}
$$

$$b = \begin{bmatrix}
15 \\
11 \\
7 \\
31
\end{bmatrix}$$

We want to solve the system above with Gaussian elimination s.t. $Ax = b$. First we import our dependencies.

In [176]:
import numpy as np
from typing import Any

We create the function gauss, which rewrites the matrix into a upper diagonal matrix.

In [177]:
def gauss(matrix: np.ndarray, answer: np.ndarray):
    number_of_variables = matrix.shape[0]
    index_vector: np.ndarray = np.arange(number_of_variables)
    maximum_vector: np.ndarray[int, Any] = np.zeros(len(index_vector))
    matrix = np.column_stack((matrix, answer))
    number_of_variables = matrix.shape[0]
    j = 0
    
    for i in range(number_of_variables):
        index_vector[i] = i
        smax = 0
        
        for j in range(number_of_variables):
            smax = max(smax, abs(matrix[i, j]))

        maximum_vector[i] = smax

    for k in range(number_of_variables - 1):
        rmax = 0
        for i in range(k, number_of_variables):
            r = abs(matrix[index_vector[i], k] / maximum_vector[index_vector[i]])

            if(r > rmax):
                rmax = r
                j = i

        switch = index_vector[j]
        index_vector[j] = index_vector[k]
        index_vector[k] = switch

        for i in range(k + 1, number_of_variables):
            xmult = matrix[index_vector[i], k]/matrix[index_vector[k], k]
            matrix[index_vector[i]] = matrix[index_vector[i]] - xmult * matrix[index_vector[k]]
            # matrix[index_vector[i], k] = 0

            # for j in range(k + 1, number_of_variables):
            #     matrix[index_vector[i], j] = matrix[index_vector[i], j] - xmult * matrix[index_vector[k], j]

        print(f"Step: {k + 1}\n", matrix, "\n")

    sorted_matrix = np.zeros(matrix.shape)
    for i in range(number_of_variables):
        sorted_matrix[i] = matrix[index_vector[i]]

    return sorted_matrix

Then we create the function solve, which solves this matrix using backwards substitution. Below you can clearly see how the Gaussian substition happens.

In [178]:
def solve(matrix: np.ndarray):
    number_of_variables = matrix.shape[0]
    answer = np.zeros(number_of_variables)
    for i in range(number_of_variables - 1, -1, -1):
        for j in range(matrix.shape[1] - 2, i, -1):
            matrix[i, -1] = matrix[i, -1] - matrix[i, j] * answer[j]
        answer[i] = answer[i] + matrix[i, -1]/matrix[i,i]

    return answer

def main():
    matrix = np.array([[2, -1, 3, 7], 
                  [4, 4, 0, 7],
                  [2, 1, 1, 3],
                  [6, 5, 4, 17]])

    answer_vector = np.array([15, 11, 7, 31])
    
    matrix = gauss(matrix, answer_vector)
    print("Upper diagonal matrix:\n", matrix)
    print("\nSolution: ", solve(matrix))

main()

Step: 1
 [[ 0 -2  2  4  8]
 [ 0  2 -2  1 -3]
 [ 2  1  1  3  7]
 [ 0  2  1  8 10]] 

Step: 2
 [[ 0  0  0  5  5]
 [ 0  2 -2  1 -3]
 [ 2  1  1  3  7]
 [ 0  0  3  7 13]] 

Step: 3
 [[ 0  0  0  5  5]
 [ 0  2 -2  1 -3]
 [ 2  1  1  3  7]
 [ 0  0  3  7 13]] 

Upper diagonal matrix:
 [[ 2.  1.  1.  3.  7.]
 [ 0.  2. -2.  1. -3.]
 [ 0.  0.  3.  7. 13.]
 [ 0.  0.  0.  5.  5.]]

Solution:  [1. 0. 2. 1.]
